name:                scripting
version:             0.1.0.0
github:              "declension/scripting"
license:             BSD3
author:              "Nick Boultbee"
maintainer:          "nick@declension.net"
copyright:           "All Rights Reserved"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/declension/scripting#readme>

dependencies:
- base >= 4.7 && < 5
- text

default-extensions:
  - OverloadedStrings

library:
  source-dirs: src
  dependencies:
    - lens-regex-pcre
    - lens


executables:
  scripting-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scripting
    - lens-regex-pcre



tests:
  scripting-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scripting
