name:                scripting
version:             0.1.0.0
github:              "declension/scripting"
license:             BSD3
author:              "Nick Boultbee"
maintainer:          "nick@declension.net"
copyright:           "All Rights Reserved"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/declension/scripting#readme>

dependencies:
- base >= 4.7 && < 5
- text

default-extensions:
  - OverloadedStrings

executables:
  scripting-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lens-regex-pcre
    - lens
